# -*- coding: utf-8 -*-
"""multiClassLogisticRegression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UNA2tsROwo5D2CKl-8UBXwi77yb2wj_k
"""

import pandas as pd
from sklearn.model_selection import train_test_split

dataset = pd.read_csv('LinedvUnHg.csv')

dataset = dataset.loc[dataset["Conc"] != 'N.S.']
dataset = dataset.loc[dataset["Conc"] != 'INS']
dataset = dataset.loc[dataset["Conc"] != '<0.01']
dataset = dataset.loc[dataset["Conc"] != '0.01']
dataset = dataset.loc[dataset["Conc"] != '1.75']
#dataset['Conc'] = dataset['Conc'].str.replace('<', '')
#dataset['Conc'] = dataset['Conc'].str.replace('N.S.', '0.0')
#dataset['Conc'] = dataset['Conc'].str.replace('INS', '0.0')
dataset = dataset.astype({"Total":"int","Unlined":"int","Lined":"int","Unknown":"int","Nearest Pond":"float", "Type":"int","Conc":"float"})
dataset

x_train, x_test, y_train, y_test = train_test_split(dataset[['Total','Unlined', 'Lined', 'Unknown', 'Nearest Pond', 'Conc']], dataset['Type'], test_size=0.4)
x_train

y_train

from sklearn import linear_model
mymodel = linear_model.LogisticRegression()
mymodel.fit(x_train, y_train)

mymodel.fit(x_train, y_train)

r_squared = mymodel.score(x_train, y_train)
print(r_squared)

mymodel.predict(x_test)

mymodel.score(x_test, y_test)

predicted_output = mymodel.predict(x_test)
predicted_output

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, predicted_output)
cm

import seaborn as sn
from matplotlib import pyplot as plt

plt.figure(figsize = (5,4))
sn.heatmap(cm, annot = True)
plt.xlabel('Predicted Value')
plt.ylabel('Truth or Actual Value')